# source("./inst/logo/logo.R")
usethis::use_logo("./man/figures/logo.png")
usethis::use_readme_rmd()
rmarkdown::render("README.Rmd")
devtools::document()
devtools::build()
devtools::install(build_vignettes = TRUE)
rstudioapi::restartSession()
library(rstanosl)